[package]
name = "ipdl_parser"
version = "0.1.0"
authors = ["Andrew McCreight <continuation@gmail.com>"]
build = "build.rs"
edition = "2018"

# Add a dependency on the regex crate; this is not
# needed if you are writing your own tokenizer by
# hand (or if you are already using the regex crate)
[dependencies.regex]
version = "0.2.0"

[build-dependencies]
lalrpop = "0.20.2"

[dependencies]
getopts = "0.2.14"
lalrpop-util = "0.20.2"
